In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_digits

In [3]:
digits=load_digits()
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [4]:
data=digits.data
target=digits.target

In [5]:
data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [6]:
target

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
type(data)
target.shape

(1797,)

In [10]:
x=[data[i] for i in range(0,len(data)) if target[i]==1 or target[i]==2]
y=[i for i in target if i==1 or i==2]
x=np.array(x)
y=np.array(y)
print(x.shape)
print(y.shape)

(359, 64)
(359,)


In [99]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
len(x_train),len(x_test)

(251, 108)

In [106]:
class LogisticRegression:
    def __init__(self,X,y,iters,alpha):
        self.iters=iters
        self.X=X
        self.y=y
        self.alpha=alpha
        self.Xsize=X[0].shape[0]
        self.ysize=y.shape[0]
        self.theta=np.random.rand(self.Xsize)
        
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))+1
    
    def updateTheta(self,hyp,y,theta):
        err=np.subtract(hyp,y)
        J=1/(self.ysize)*(np.dot(err,self.X))
        theta=theta-(self.alpha*J)
        return theta
        
        
    def fit(self):    
        for i in range(0,self.iters):
            hyp=self.sigmoid(np.dot(self.X,self.theta))
            self.theta=self.updateTheta(hyp,self.y,self.theta)

    def predict(self,x):
        y_pred=self.sigmoid(np.dot(x,self.theta))
        y_pred=np.array([int(i>=1.5)+1 for i in y_pred])
        return y_pred
    
    def score(self,x,y):
        return 1-(np.sqrt(np.mean((self.predict(x)-y)**2)))
    

In [107]:
lreg=LogisticRegression(x_train,y_train,110,0.02)

In [108]:
lreg.fit()

In [109]:
hyp=lreg.predict(x_test)
hyp

array([1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1,
       2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1,
       2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2,
       1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2,
       1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1])

In [110]:
hyp-y_test

array([ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [111]:
print("accuracy score: ",lreg.score(x_test,y_test)*100)

accuracy score:  80.75499102701247


In [105]:
x_test

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  7., ..., 14., 11.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0., 11., ..., 16., 16.,  6.],
       [ 0.,  0., 13., ...,  3.,  0.,  0.]])